### PR TITLE
Fix report problems and change the way grades are updated

### PR DESCRIPTION
**Pull request by antonio-c-mariani**
This pull request covers the issues #188, #163, #127 and #38. I've tried to separate the report fixing issues from the upgrade grades issues but it's no easy because they are very related.

The function "attendance_get_users_points" calculates the users points. These data are used both to build the report summaries and to upgrade grades. All other changes go around this.

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks Antonio, will be good to tidy up some of the way the grade stuff/reporting is done - I'm pretty busy at the moment and this is likely to require a bit of testing/review - I notice the travis checks are failing on coding guideline issues and a behat test now fails so if you could fix those up too it would be great.

also - I see some big changes to sql statements - have you tested these on PostGres or just MySql? - might be nice to add some more behat tests if possible so we can cover the reports/grading changes too.

**Comment by antonio-c-mariani** [comment]
I have fixed some coding guideline issues. There are many other that were there before the changes.

I do not know much about behat tests. It seems the fail was there before the changes. Could you please check this? I'll try to write new behat tests as you ask.

About SQL statements, some of them was removed and just one is new (attendance_get_users_points function). Yes, I have tested it under PostGres.

Let me know if you have any questions or suggestions about the changes.

**Comment by danmarsden** [comment]
Hi Antonio, thanks for fixing up those coding guideline issues with your code -  the travis checks run on each build and they are passing as of last commit in the main branch: 
https://travis-ci.org/danmarsden/moodle-mod_attendance/builds/120556397

the existing violations and warnings in existing code can be ignored and do not result in a build failure but the behat failures appear to relate to the changes you have made - it's possible that the behat tests are now incorrect and are looking for the wrong data but we cannot merge code that causes the travis checks to report a fail. Ideally your code should not introduce any "new" warnings if possible too. (there are still a few being reported in the build linked above.) 

I'm away most of this week but will try to pick this up again and look at it properly when I get back.

thanks!

**Comment by antonio-c-mariani** [comment]
Hi, Dan

I believe I have identified the failure. I need your help to see what to do.

See the pictures below for the student 3. The student has grade 0/0 because there is no taken attendance for him. In the current version it appears in the "Low grade" report.

gr1

gr2

The condition for the student to be shown at the "low grade" report is set in line 510 of file renderables.php:
   if ($att->pageparams->view != ATT_VIEW_NOTPRESENT || $grade < $maxgrade) {

The value of the variable $maxgrade is set a few lines before:
   $maxgrade = attendance_get_user_max_grade(count($this->sessions), $this->statuses);
that calculates the value 4 for the present scenario. As 0 < 4, the student 3 is included in the "low grade" report.

In the new version, the function "attendance_get_user_max_grade" was removed because it fails when working with multiple status set. The "maxgrade" (maxpoints) value is now calculated by the "attendance_get_users_points" function, resulting in the value 0 (zero) because there are no taken sessions for this student. This seems to be consistent with the value that is displayed in the attendance reports. But because of this the student is not included in "low grade" report, causing the failure at the behat test.

In the new code the line 510 was changed to:
   if ($att->pageparams->view != ATT_VIEW_NOTPRESENT || $points < $maxpoints) {
A simple solution seems to be changing this line to:
   if ($att->pageparams->view != ATT_VIEW_NOTPRESENT || $points < $maxpoints || $maxpoints == 0) {
What do you think about? Do you have any other suggestions?

**Comment by danmarsden** [comment]
thanks Antonio - as mentioned in the other pull request, can you please squash these commits and include the github issue # in the commit messages to tidy it up a bit? - thanks!

**Pull request closed without merging**
