### PR TITLE
Amend required version to 2022031100 (Moodle 4.0)

### PR DESCRIPTION
**Pull request by lucaboesch**
Your required version was wrong.

### CODE REVIEW

**Comment by danmarsden** [comment]
Actually the comment is wrong there. This is the 4.1 required branch...

**Comment by danmarsden** [comment]
(See the 400_stable branch for 4.0 support.)

**Comment by lucaboesch** [comment]
Okay, Dan, all good, but then, please, call the 4.1 branch MOODLE_410_STABLE.
I took that MOODLE_401_STABLE one since on Moodle 4.0.4 (and I thought: 'oh, that's larger than 4.0.1') and installation broke.

Best,
Luca

**Comment by danmarsden** [comment]
410 stable is wrong. It is not 4.10 it's 4.1 otherwise referred to as 401 (see upstream examples)

**Comment by danmarsden** [comment]
the new naming happening on the 310 release - going from 2 digit release names to 3 eg:
MOODLE_310_STABLE (3.10)
MOODLE_311_STABLE (3.11)
MOODLE_400_STABLE (4.0)
MOODLE_401_STABLE (4.1)

**Comment by lucaboesch** [comment]
I was making a fool of myself. Now I get it finally that MOODLE_410_STABLE would be 4.10.
Please apologize.

**Comment by danmarsden** [comment]
nope - it's tripped up several devs here in the team too - I've had to explain this a few times to different people :-) - I'm not a big fan of the new naming convention - it's also mixed in a few different places - some places use 4.1, some places use 401 - it didn't help that it wasn't listed in the readme here, and the comment in version.php was wrong either!

**Pull request closed without merging**
