### PR TITLE
#351 Added Attendance password rotation/expiry

### PR DESCRIPTION
**Pull request by Bellangelo**
It does not save old passwords or expire them because it shows a timer when the password will be changed.

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks - it doesn't look like you have understood the requirements here - if you are trying to improve your GSOC application you should work on some other unrelated tasks that demostrate your ability to understand the issue/problem solve and follow our guidelines/procedures. Thanks.

**Comment by Bellangelo** [comment]
Thank you for your comments. Could you please elaborate what is wrong with my code? Or you mean that this project should be a full time project for the summer?

**Comment by danmarsden** [comment]
Yes - this was supposed to be part of the project work, but the main issue not considered here is server performance and only storing 2 "passwords" - I'd prefer to see multiple passwords generated and then rotated without requiring a call to the server every time the QR code changes - I'm happy to provide more feedback such as coding guideline issues, namespacing issues, how to handle inclusion of 3rd party code, but this also means that you will need to think about what to include in your project proposal if all the work is completed prior to GSOC. 

thanks!

**Comment by Bellangelo** [comment]
Thank you very much for your help! I now understand more the project. Thanks again!

**Pull request closed without merging**
