### PR TITLE
Performance increase on 2022090900 upgrade step.

### PR DESCRIPTION
**Pull request by jwcatau**
PostgreSQL performance increase for sites with large numbers of records in {attendance_log}.

Step 2022090900 upgrade on a database with 1.3 million records (3 duplicates) took 21-24+ hours and with the fix took 33 seconds.

Instead of a `DELETE ... WHERE NOT IN` this approach uses a `SELECT` to create a new "temporary" table, `TRUNCATE` the old one, re-`INSERT` the records back, and `DROP` the working table, in a delegated transaction.

```
# Total records in the table
moodle=# SELECT COUNT(*) FROM mdl_attendance_log;                                                             
  count  
---------
 1342090  
(1 row)

# Unique records not to be deleted from SQL sub-select:
moodle=# SELECT COUNT(1) FROM (SELECT max(id) FROM mdl_attendance_log GROUP BY sessionid, studentid, statusid) data;
  count                   
---------                                                                                                                                                                                                          
 1342087                                                                                                                                                                                                           
(1 row)                                


# Before SQL change:
-->mod_attendance
...
++ 2022090900: Success (75622.90 seconds) ++

# After SQL change:
-->mod_attendance
...
++ 2022090900: Success (33.51 seconds) ++
```

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks James... I'm not all that keen on creating a temp table then deleting it to be honest - surely there are better ways to de-duplicate records in a postgres table than using a temp table like this?

**Comment by jwcatau** [comment]
Yes, @danmarsden - I agree, it feels clunky and awful - but it resulted in a massive speed increase. (And I noticed I had a typo in my other PR, which I may need to fix up in the PR). 

P.S. And I haven't verified the data records to the level I would have liked, but looking for more pairs of eyes.

**Comment by petersistrom** [comment]
Hi @danmarsden and @jwcatau, 
I have created a new patch to improve the upgrade performance which has similar performance improvements to the one above without the need for a temp table. I can create a new pr or @jwcatau if you're happy with it can you change the branch in this PR?
https://github.com/petersistrom/moodle-mod_attendance/commit/33c98b245c368c7ea2f125dcf4ce41e3e9dbbb9c
https://github.com/petersistrom/moodle-mod_attendance/tree/MOODLE_401_STABLE_pgsql_upgrade_performance

Thanks,
Peter

**Comment by danmarsden** [comment]
Thanks Peter - yeah that looks like something I'd be happier to merge - thanks!

**Comment by petersistrom** [comment]
I've create new PR with the updated fix - https://github.com/danmarsden/moodle-mod_attendance/pull/710

**Comment by jwcatau** [comment]
Thanks, @petersistrom - closing this poor attempt of mine off!

**Pull request closed without merging**
