### PR TITLE
Added "mod_attendance_get_sessions" API function

### LINKED ISSUE #554: Add API method to retreive session id's by AttendanceInstanceId
Hi,
Several API methods currently depend on the session id be provided. However, there seems to be no current API function to get all session id's for an attendance instance in a course.

Kind regards,
Peter

### PR DESCRIPTION
**Pull request by pete1854**
Adding API function for retrieving all session instances for a given attendance instance.
Fixes #554

### CODE REVIEW

**Comment by pete1854** [comment]
Typo in previous commit description: "Returned" should be "Removed".

**Comment by danmarsden** [comment]
Thanks @pete1854  - all of the existing webservices are covered by unit tests in tests/externallib_test.php - any chance you could add a test for this new function there as well? - thanks!

**Comment by pete1854** [comment]
Hi @danmarsden - I've added a unit test for the new API function. To be honest I do not have a complete dev environment set up for PHP development (I'm a C# developer), so it's very likely they will fail due to some syntax error (because I haven't run the test myself). Maybe you can correct this, should it be necessary? Thanks, Peter

**Comment by danmarsden** [comment]
thanks @pete1854 - the behat errors there look unrelated to your patch - I'll see if I can find some time to look at them before I merge this in.

**Pull request merged**
