### PR TITLE
Changing default users sort order to users_order_by_sql moodle function

### PR DESCRIPTION
**Pull request by antonio-c-mariani**
See #207.

### CODE REVIEW

**Comment by danmarsden** [comment]
cool - great to see this, it's something I've wanted to do for a while too - I haven't looked at the code yet but I see a behat failure there - any chance you could take a look at that before I merge it?

**Comment by antonio-c-mariani** [comment]
I need your help because I really don't know what is happening.

The changes are very simple and don't affect (should not) the interface. When I saw the behat failure I run a test locally and it was there. But now I'm not able to reproduce it. Look the picture below that shows the result of the test:

behat_firefox

And here is a print screen where you can see de "Submit attendance" string.

att1

Any idea?

**Comment by antonio-c-mariani** [comment]
I just closed and reopened the pull request and the failure disappeared. It seems there is some problem with the behat tests related to the time when a pull request is submitted.

**Comment by danmarsden** [comment]
looks ok to me - thanks Antonio! - not sure what's going on with behat at the moment.

**Pull request merged**
