### PR TITLE
Added support for scales

### PR DESCRIPTION
**Pull request by greg-or**
Hoping to solve issue #51

### CODE REVIEW

**Comment by danmarsden** [comment]
thanks - looks like it might be doing the right stuff - I've been super-busy so haven't had time to spend on attendance recently - I'll try to find the time within the next couple of weeks!

**Comment by cedict** [comment]
No worries Dan. I just updated the pull request to take into account the att_update_all_users_grades function.

**Comment by danmarsden** [comment]
thanks - looks like it's doing the right stuff so I've merged it across (I presume you guys have tested it at flinders?) :-)

**Comment by danmarsden** [comment]
whoops - looks like there's a regression here:
Fatal error: Using $this when not in object context in /home/dan/www/moodle-r2/mod/attendance/locallib.php on line 1722

**Pull request merged**
