### PR TITLE
WR359500 pull request

### PR DESCRIPTION
**Pull request by SimonThornett**
Fixes/enhancements for the following

* Add functionality to allow editing teachers on a course to import a CSV file of sessions to a particular Attendance activity
* Support repeating sessions https://github.com/danmarsden/moodle-mod_attendance/issues/494
* Fails to set password when importing CSV https://github.com/danmarsden/moodle-mod_attendance/issues/510
* When setting a session allow for the selection of individual minutes - https://moodle.org/mod/forum/discuss.php?d=419472#p1690416

### CODE REVIEW

**Comment by danmarsden** [comment]
thasnks @SimonThornett can you please submit a PR for the lastest branch first?  (MOODLE_400_STABLE) we can then backport to the other branches as required.

**Comment by SimonThornett** [comment]
Hi Dan,

Sorry meant to email you sooner but have been off. Client noticed an issue
with the QR codes on the password display due to conflicting settings from
the import, just need them to test a fix and I'll reimplement on the latest
branch and submit a PR.

Kind regards,
Si

**Comment by danmarsden** [comment]
haha - forgot I'd emailed you.... just got back from leave and was mindlessly going through the backlog... :-)

**Comment by wilenius** [comment]
Hi, I'd love to take this branch for a test drive, but should I wait for @SimonThornett's new version? CSV import would be a big thing for our organisation... Please let me know if I can help with testing.

**Comment by SimonThornett** [comment]
Hi @wilenius,

I'm working on re-branching this from MOODLE_400_STABLE like Dan requested as we speak (sorry for the hold up). Hopefully once done Dan can add this to the main repo.

Si

**Comment by wilenius** [comment]
Hi @SimonThornett, that's great news!

**Comment by SimonThornett** [comment]
@danmarsden,

I've rebased from MOODLE_400_STABLE and updated this pull request. Testing has been done by our clients, but @wilenius if you find anything please let me know and I'll have a look.

Si

**Comment by wilenius** [comment]
Thanks! So, import/sessions.php defines the supported variables in the .csv row header, right? I'll give this a spin in a few days.

**Comment by SimonThornett** [comment]
For the activity level import it uses the same headers as the global one from the classes/import/sessions.php::read_mapping_data method, just without the course "course" header.
You can see a list of these here too:
https://docs.moodle.org/400/en/Attendance_activity#Adding_Sessions_in_Bulk

**Comment by wilenius** [comment]
Thanks, yeah, makes sense! Forgot that admins already had the import feature.

**Comment by danmarsden** [comment]
@SimonThornett - looks like this is bringing back the old renderables.php file - in the main branch those classes were all split out into their own files ... hopefully you didn't have many changes in the renderer classes that need to be ported over to their new/correct locations.

**Comment by SimonThornett** [comment]
Ah, damn, sorry about that, I'll get that corrected now

**Comment by SimonThornett** [comment]
Running additional tests now, will confirm when ready for review

**Comment by SimonThornett** [comment]
@danmarsden, That's all been updated now and the renderables.php is back to what it was and the new import tab added to the classes/output/tabs.php file. I've tested this locally with the same steps I had before, and the import works as expected.

Si

**Comment by danmarsden** [comment]
Awesome thanks! I should be able to test and merge this tomorrow

**Comment by wilenius** [comment]
Sorry for spamming the pull request thread again, but: are you planning to backport this to 3.11?

**Comment by danmarsden** [comment]
I'm not, but @SimonThornett might send me a PR to backport it - I think he has a client running it on 3.9 so lets see... :-)

**Comment by aspark21** [comment]
FYI - this caused #597

**Comment by danmarsden** [comment]
Thanks, looks like behat failures aren't triggering the actions to fail.  Feel free to submit a pr to fix otherwise I'll take a look tomorrow

**Comment by wilenius** [comment]
I've tested this now on our 4.0 test server, and it seems to work nicely. @SimonThornett, do you have plans to backport this to 3.11? Any thoughts how much work that would be?

**Comment by SimonThornett** [comment]
@wilenius, I'll sort 3.11 and 3.9 backports over the weekend and sort the PRs Monday morning

**Pull request merged**
