### PR TITLE
allsessionsreport

### PR DESCRIPTION
**Pull request by nwp90**
Partial fix for #373, but actually motivated by our own internal needs.

- The intent is to add a report on a single student across the entire Moodle instance.
- I've tried to keep changes to existing code minimal, but I think in a few places a little tweaking was necessary.
- I've kept what I've added (painfully) straightforward for now; once/assuming it gets merged, IIRC a fair bit of refactoring would make sense.
- In particular, even though the desired output is different, the structure of the query in get_user_sessions_log_full (added here), as opposed to the two queries in (the existing) get_user_sessions_log_extended should be significantly faster and I think more correct (the existing function does not get all the sessions it implies it should).
- The new report is fairly wide - it may be that things will need tweaking to work well with small screens or certain themes.

### CODE REVIEW

**Comment by nwp90** [comment]
Forgot to mention - haven't yet added the ability to edit the attendances. There is a gap left for that at the moment.

**Comment by nwp90** [comment]
Oops. Seems I'd inadvertantly included a separate fix too:

`{
  "sites": {
    "med": {
      "dbport": 5432,
      "dbhost": "asterix",
      "dbname": "moodle2_otagounifom",
      "dbuser": "moodle2_webuser",
      "dbpass": "",
      "prefix": "mdl",
      "repo_path": "/mnt/hcs/moodle_repositories/common_repository",
      "data_path": "/var/lib/sitedata/moodle-site-otagounifom"
    },
    "hsmdl": {
      "dbport": 5432,
      "dbhost": "asterix",
      "dbname": "hsmoodle_otagounifom",
      "dbuser": "hsmoodle_webuser",
      "dbpass": "",
      "prefix": "hsmdl"
    }
  },
  "services": {
    "wimpycal": {
      "baseurl": "https://wimpy.otago.ac.nz",
      "token"  : ""
    },
    "medcal": {
      "baseurl": "https://medschool.otago.ac.nz",
      "token"  : ""
    }
  },
  "default_site": "med",
  "default_service": "wimpycal",
  "default_report": ""
}
`
It's good, but it should be in its own ticket...

**Comment by nwp90** [comment]
Adding the edit functionality ran very much counter to a lot of assumptions in the existing code; I've duplicated bits in various places to make this work with minimal modification to existing code. I figured it would be better to get to the end and then take stock to see what if any refactoring would make sense.

**Comment by nwp90** [comment]
Will be updating this with events on view/update once #411 is fixed.

**Comment by nwp90** [comment]
OK, updated to latest master, incorporating & updating the session report viewed event to build an "updated" event on top of it.

**Comment by nwp90** [comment]
Rebased, fix for missing groupby & extra whitespace found by travis.

**Comment by danmarsden** [comment]
fyi - this got closed "automatically" as I renamed the "master" branch to "main" - I'll see if there's a way I can reopen this soon.

**Comment by nwp90** [comment]
Can always recreate it and link to this one if necessary.


Cheers,


Nick

**Pull request closed without merging**
