### PR TITLE
More webservice functions.

### PR DESCRIPTION
**Pull request by kabalin**
This PR contains new webservice functions, namely:

* `mod_wsattendance_add_attendance`
* `mod_wsattendance_remove_attendance`
* `mod_wsattendance_add_session`
* `mod_wsattendance_remove_session`

They are designed to facilitate remote session creation in courses. All functions contain permission validation. Also basic permission check has been added to all existing webservice functions. Unit test coverage for all new functions has been added as well.

As side note, I think it might be good idea to rename functions (no idea about impact) to match common naming convention (e.g. `mod_attendance_*` instead of `mod_wsattendance*`). I can add commit if needed.

The work on those changes has been funded by WKS KV Bildung (https://www.wksbern.ch).

### CODE REVIEW

**Comment by danmarsden** [comment]
yeah - good call - can you please rename all your new services to mod_attendance and then I'll create a new MOODLE_37_STABLE branch that has your new mod_attendance services and the old mod_wsattendance services, but in master we'll rename all the wsattendance services to attendance. (I don't want to rename them in a stable branch, but we should do this in a master (3.8 and higher) branch.

**Comment by kabalin** [comment]
Hi Dan, thanks for revision. I renamed functions per your request. I also addressed Travis outcomes.

I'll be happy to submit another commit renaming all webservices, ping me know when 3.7 branch is ready and I will create another PR to master :)

**Comment by danmarsden** [comment]
Thanks - looking good so far, but looks like there's some debugging warnings that are causing the behat tests to fail - any chance you could take a look to see what's going on there?

**Comment by kabalin** [comment]
Hi @danmarsden, everything should be good now.

**Comment by danmarsden** [comment]
merged in thanks! - I've created 3.6/3.7 branches now as well, (with your updated code) - if you want to file a new pull request to rename those mod_wsattendance ones that would be cool! - no worries if you don't get to it, I'll find some time to do that on my end if needed. Thanks!

**Comment by danmarsden** [comment]
just noticed this changes seems to have broken the update_user_status function - missing global $DB and undefined var: $attforsession used - I'll create a new issue to look at this later.

**Pull request merged**
