### PR TITLE
First part of "rooms" implementation

### PR DESCRIPTION
**Pull request by flocko-motion**
This is the first step towords a "rooms" implementation for mod_attendance. It creates the ability to create/edit/delete rooms in the plugin config and allows session creators/editors to select a room where the session takes place. 

The current version passes all tests on travis-ci

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks! Quite busy here at the moment but I'll try to take a look soon!

**Comment by flocko-motion** [comment]
I implemented the next step: when "rooms" feature is activated, session creators can select a room and a max amount of participants. Students can "book" into a session until max capacity is reached. Session table shows, how many students booked into which session.

Yet to do: check for double bookings when creating a session, write phpunit and behat tests (I'm currently learning the behat syntax)

**Comment by flocko-motion** [comment]
By the way: you can ignore all commits before october 20th - because on that day I reverted everything to the original version of the plugin and restarted my implementation with more knowledge about moodle and the plugin than I had the first time.

**Comment by danmarsden** [comment]
Hey @flocko-motion - haven't forgotten about this - but insanely busy here at the moment - will hopefully come back to this at some point and take a look.

**Comment by flocko-motion** [comment]
Hi Dan,

Thanks for writing - no problem at all. I have decided in the meantime to
hard fork my project off from mod_attendance as my requirements list is too
different from the current implementation. Therefore I now removed all
unneeded code to clean up, rewrote the complete UI using mustache giving it
a more modern, cleaned up look and am now adding all the features that my
client school requires. I have to move fast and break things to be able to
finish according to schedule.

Programming the "rooms" feature I was paying a lot of attention on being
minimal invasive and respecting all the rules. This feature is meant as a
contribution and pay-of-respect to the existing code base that I'm
profiting of for my project. If you include it in the plugin I will be
happy to provide a few more updates e.g. a double-booking checker for the
rooms..

Cheers,
Flo


Am So., 22. Nov. 2020 um 21:30 Uhr schrieb Dan Marsden <
notifications@github.com>:

**Comment by danmarsden** [comment]
Thanks @flocko-motion - now that you've forked it makes it even harder to review this PR so I'm closing it off - unfortunately your git branch history is also too hard to review with lots of those early commits. Unless someone wants to fund my time to take a look at this and rewrite it to meet Moodle coding guidelines I'm not in a position to review the code in the form you have submitted it here - hope the project goes well and glad you were able to re-use the attendance plugin codebase!

all the best!

**Pull request closed without merging**
