### PR TITLE
Adding calendar events creating, updating and deleting

### PR DESCRIPTION
**Pull request by Disss**
Hi,
I've implemented events creation on plugin update at last and updated backup/restore feature to work properly with the events. Hope that will do.

### CODE REVIEW

**Comment by Disss** [comment]
Okay, there's definitely something broken about those behat tests. It corresponds to 100% valid code (which this commit does not affect). And by the way now it fails on all configuration (not only pgsql as it was before).
Checked it before pull request - [travis-ci.org/Disss/moodle-mod_attendance](url) - worked well.

**Comment by Disss** [comment]
Hey @danmarsden, is there anything yet to be done with this plugin modification?

**Comment by danmarsden** [comment]
sorry - it's been a busy few weeks - hopefully will have time to review/test this sometime later this week - bug me again next week if I haven't looked at it again! - thanks.

**Comment by Disss** [comment]
Bumping this thread. Hope you'll have time for review this week. Thanks.

**Comment by danmarsden** [comment]
thanks for working on this - code looks great, makes sense and looks like you've covered it well - great work! - I know a lot of people will be happy to see this land!

**Pull request merged**
