### PR TITLE
Upload Attendance Feature #2

### PR DESCRIPTION
**Pull request by jonathanchan2**
I accidentally deleted my remote branch resulting in the associated pull request #383 being permanently closed. I tried a number of methods to try and reopen the pull request but nothing seemed to work. So I have decided to open a new pull request to continue from where the last pull request left off. 

Thank you for understanding,
Jonathan

### CODE REVIEW

**Comment by danmarsden** [comment]
no worries - sometimes it's easier that way anyway! :-)

Thanks - this looks like a much cleaner patch - I'll try to take a close look and test it this week!

**Comment by jonathanchan2** [comment]
Hi Dan,

How is the testing going so far?

**Comment by danmarsden** [comment]
sorry - crazy busy last week, looking a bit crazy this week too but will try to find some time for this.

**Comment by jonathanchan2** [comment]
Hi Dan, 

Did you get an opportunity to do any testing as yet?

**Comment by danmarsden** [comment]
Hi Jonathan - unfortunately not - this just keeps slipping as I work on jobs I am paid to do.. I will get to it soon, but will be away next week at the AU Moot and may not have time to look at it again for a couple of weeks. It is very high on my list, but becuase of the size/impact of this patch it needs me to have a decent chunk of time to dedicate to look at it properly. Thanks!

**Comment by jonathanchan2** [comment]
Hi Dan,

I understand your situation. I would also focus on my paying job if I were in your shoes. I am just really really excited to get this feature out there into the hands of the many users who have been asking for it a while now. I can check back with you in a couple weeks to remind you if you would like.

**Comment by jonathanchan2** [comment]
Hi Dan,

I am checking back with you to see if you got an opportunity to look at the attendance upload feature I uploaded.

**Comment by danmarsden** [comment]
sorry - still haven't managed to look at this properly yet! - I've cleared a few of the other items in the backlog though so hopefully I'll get to it soon! - thanks for your patience!

**Comment by randywreed** [comment]
I just wanted to check and see what the status of the feature update is? Its something I could really use.

**Comment by nadavkav** [comment]
+1 for getting this into mod/attendance

**Comment by danmarsden** [comment]
yeah +1 from me too ;-)

finding "volunteer time" has been a bit more of a challenge than normal and I've already spent a massive amount of volunteer time on this one via previous pull requests. The current pull request is definitely "better" but still needs a decent chunk of time from me to test and re-work a few areas. Hopefully I'll get to it at some point!

**Comment by nadavkav** [comment]
I must say that I am happy to read that you do not have spare time for volunteering, I think it is a good sign :-)

**Comment by danmarsden** [comment]
haha - yeah - lucky to have lots of things to keep me busy! :-)

**Comment by danmarsden** [comment]
fyi - this got closed "automatically" as I renamed the "master" branch to "main" - I'll see if there's a way I can reopen this soon.

**Pull request closed without merging**
