### PR TITLE
Fix behat failures

### PR DESCRIPTION
**Pull request by gthomas2**

### CODE REVIEW

**Comment by danmarsden** [comment]
Do you have context for this? Might need to be aware there's currently a failure in master branch due to a regression in formslib related to the new hiddenif stuff.

**Comment by danmarsden** [comment]
the fact that you've changed the case of the AM/PM text in the behat tests makes me wonder if you have made local changes to the lang files that are causing failures for you. (or maybe you're running behat in en_us instead of en?) looks like behat is failing to run on your changes (not sure why) but I suspect if they run they will fail on the core code.

**Comment by gthomas2** [comment]
I just downloaded the plugin and tried running the behat tests for it on a vanilla Moodle 3.3.

For the AM / PM case sensitivity issue -perhaps the 'AM / PM' text is generated by PHP date/time formatting and there could be some variance between either PHP versions or the default locale for PHP. I will work on a better fix for this today.

I also found another issue where Behat would try to enter attendance data before the form was available, so I added this step to work around that:

I wait until attendance table is visible

**Comment by gthomas2** [comment]
I have two completely separate environments with PHP installed, one on osx and the other on ubuntu.
On osx %p results in "am" and on ubuntu it results in "AM". The CI environment where I work resolves %p to "am" but the development image we use resolves %p to "AM". I can write a custom step which will work with either.

**Comment by gthomas2** [comment]
After some digging it seems like PHP support for %p is hit and miss.

http://php.net/manual/en/function.strftime.php

"Not all conversion specifiers may be supported by your C library, in which case they will not be supported by PHP's strftime()"

**Comment by gthomas2** [comment]
I've fixed the behat failures in a way that will accept %p being output differently in some environments. The alternative solution to this would be to modify the existing code to force the case of anything formatted with %p.

**Comment by danmarsden** [comment]
Thanks for the context - I hadn't seen this because Travis runs on ubuntu and we run all our CI tests on ubuntu here at Catalyst too.  I'm not sure what I think about "I wait until attendance table is visible" - (is that really needed and under what conditions can you reproduce that as an issue?)

it sounds like we might need to change the %p to something else if it's not very reliable. We changed them recently in #262 to improve compatibility with Windows machines - but I didn't look at compatability with MacOs.

**Comment by gthomas2** [comment]
I was wondering if we could swap to using the PHP date function to get 'am' or 'pm' but sadly it does not localise.
However, after searching for problems with people using %p it seems that it does not localise for certain languages correctly - e.g. Spanish:

https://stackoverflow.com/questions/6852947/strftime-doesnt-show-pm-or-am

So the localisation benefits of using strftime to print out "AM" or "PM" are pretty limited.

**Comment by danmarsden** [comment]
you can change it in the lang packs for languages that don't support %p - but it sounds like it's not just locales that don't support it but the Web server itself that may not support it either.

**Comment by gthomas2** [comment]
For the "I wait until attendance table is visible" step, it fixed an intermittent failure and I can't reproduce it now. Basically mink would try to click on things in the attendance table and it couldn't because the attendance table wasn't available. I could probably remove the "I wait until" steps if you like.

**Comment by danmarsden** [comment]
yeah - I'm not a fan of adding code "just because" so the "I wait until attendance table is visible" is probably a non-starter. Also - although your patch will make the tests pass on a wider range of systems I'm not sure it's really the right way forward. We might need to modify the strftime string to something that is more cross-platform compatible. Issue #273 is a recent one from a user on CentOS where the %p doesn't appear to be working either.

**Comment by danmarsden** [comment]
here's what I was thinking might be a better method:
https://github.com/danmarsden/moodle-mod_attendance/commit/6fa7ca8655a28bb46386c69d616360ad93a17364

what do you think?

**Comment by danmarsden** [comment]
- with a clearer head, that patch isn't quite right because each locale may use a different value for AM/PM - what we might need to do is check if %p is included in the string, remove it and compare the result with and without the %p - if the result is exactly the same (with and without %p) then add the english version of AM/PM depending on the %p or %P - make sense?

**Comment by gthomas2** [comment]
Yes, that makes sense. I like the approach ;-)

**Comment by danmarsden** [comment]
cool - closing these pull requests and I'll try to fix that patch up today - thanks for the report and discussion!

**Comment by gthomas2** [comment]
No worries! And kudos to you for having behat tests that revealed a problem ;-)

**Comment by danmarsden** [comment]
2nd time this week that the behat tests have picked something up which is nice for a change! - it picked this up in the moodle master branch: https://tracker.moodle.org/browse/MDL-60012

**Pull request closed without merging**
